name = "flyer"
compatibility_date = "2024-05-02"

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

[[kv_namespaces]]
binding = "KV"
id = "${KV_NAMESPACE_ID}"